name: Generate Sitemap
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: "https://graphattentionnetwork.github.io"
      - name: Commit and push sitemap
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sitemap.xml
          git diff --staged --quiet || git commit -m "Update sitemap"
          git push
